### ISSUE TITLE
roadmap v0.1.0

### ISSUE THREAD

**Issue by hsinatfootprintai** [FootprintAI/virtuscale#3]
virtuscale provides native integration to the underlying backend (e.g. kfp). This doc lists feature requests available.

- training
- [x] support TensorFlow 
- [ ] support PyTorch
- [ ] support multi-step training architecture
- [ ] add training metrics with push model
- [ ] support model registry

- model storage
- [ ] support pvc & s3
- [ ] support versioning
- [ ] support copy and tags (like dockerimages)

- inferencing
- [ ] support kserve 
- [ ] support swagger
- [ ] support inferencing metrics
